create table if not exists public.feedback_submissions (
  id bigint generated by default as identity primary key,
  feedback_type text not null check (feedback_type in ('general_feedback', 'feature_request', 'bug_report')),
  subject text not null,
  message text not null,
  name text null,
  email text null,
  product text not null default 'AI Solution Maven',
  page_path text null,
  page_url text null,
  source_context text null,
  share_id text null,
  plan_title text null,
  severity text null check (severity in ('low', 'medium', 'high', 'critical')),
  steps_to_reproduce text null,
  desired_outcome text null,
  browser text null,
  user_agent text null,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists feedback_submissions_created_at_idx
  on public.feedback_submissions (created_at desc);

create index if not exists feedback_submissions_type_idx
  on public.feedback_submissions (feedback_type, created_at desc);

alter table public.feedback_submissions enable row level security;

drop policy if exists "Public insert feedback submissions" on public.feedback_submissions;
create policy "Public insert feedback submissions"
on public.feedback_submissions
for insert
with check (true);
