import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ShareViewFooterCta } from "@/components/plansight-ai/ShareViewFooterCta";
import { SharedStakeholderPlanLoader } from "@/components/plansight-ai/SharedStakeholderPlanLoader";

export const runtime = "nodejs";

type Props = {
  params: Promise<{ shareId: string }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { shareId } = await params;

  return {
    title: `Shared plan — PlanSight AI`,
    description: "Read-only stakeholder view generated by PlanSight AI.",
    // Share pages are unguessable by design; keep them out of search indexes.
    robots: { index: false, follow: false },
    icons: {
      icon: [
        { url: "/products/plansight-ai/favicon.ico", sizes: "any" },
        { url: "/products/plansight-ai/favicon-32.png", type: "image/png", sizes: "32x32" },
        { url: "/products/plansight-ai/favicon-16.png", type: "image/png", sizes: "16x16" }
      ],
      apple: { url: "/products/plansight-ai/favicon-180.png", sizes: "180x180" }
    },
    alternates: { canonical: `/share/${shareId}` }
  };
}

export default async function SharePage({ params }: Props) {
  const { shareId } = await params;

  return (
    <main className="min-h-screen bg-white">
      <header className="h-16 border-b border-slate-200 bg-white px-6">
        <div className="mx-auto flex h-full max-w-[1600px] items-center justify-between gap-4">
          <Link href="/products/plansight-ai" aria-label="PlanSight AI" className="shrink-0">
            <Image
              src="/products/plansight-ai/brand/plansight-logo-primary.svg"
              alt="PlanSight AI"
              width={180}
              height={36}
              priority
              className="h-8 w-auto sm:h-9"
            />
          </Link>
        </div>
      </header>

      <SharedStakeholderPlanLoader shareId={shareId} />

      <ShareViewFooterCta shareId={shareId} />
    </main>
  );
}
