"use client";

import { HelpCircle, X } from "lucide-react";
import { useEffect, useState } from "react";

/**
 * "What is this?" trigger plus the explanation modal it opens. Owns its
 * own open/closed state — drop near the AI Analysis tab header (or any
 * AI surface) and it works standalone.
 *
 * Modal copy is the full version from
 * docs/plansight-ai/specs/IN_PRODUCT_DISCLAIMERS_SPEC.md §Surface 4.
 */
export function AiAnalysisAbout() {
  const [open, setOpen] = useState(false);

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        className="inline-flex items-center gap-1 text-caption text-cyan-700 underline-offset-2 transition hover:text-cyan-800 hover:underline"
      >
        <HelpCircle className="h-3.5 w-3.5" />
        What is this?
      </button>
      {open ? <AboutModal onClose={() => setOpen(false)} /> : null}
    </>
  );
}

function AboutModal({ onClose }: { onClose: () => void }) {
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [onClose]);

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="ai-about-title"
      className="fixed inset-0 z-50 flex items-center justify-center bg-navy/70 px-4"
      onClick={onClose}
    >
      <div
        onClick={(event) => event.stopPropagation()}
        className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-xl border border-slate-200 bg-white p-6 shadow-modal"
      >
        <div className="flex items-start justify-between gap-4">
          <h3 id="ai-about-title" className="text-h3 text-ink">
            About AI Analysis
          </h3>
          <button
            type="button"
            onClick={onClose}
            className="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-md text-slate-500 transition hover:bg-slate-100 hover:text-slate-700"
            aria-label="Close"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        <div className="mt-4 space-y-4 text-body text-slate-700">
          <p>
            AI Analysis is generated by Claude, an AI model from Anthropic,
            based on the structured task data in your uploaded plan. It
            produces three things:
          </p>
          <ol className="ml-5 list-decimal space-y-1">
            <li>A narrative summary of the plan&apos;s current state</li>
            <li>Identified risks, referencing specific tasks</li>
            <li>Prescriptive recommendations the PM can consider</li>
          </ol>

          <p className="pt-2 text-h3 text-ink">What it does NOT do</p>
          <ul className="ml-5 list-disc space-y-1">
            <li>
              Replace human project management expertise or professional
              judgement
            </li>
            <li>
              Guarantee accuracy — AI can make errors, miss context, or
              produce outdated assessments
            </li>
            <li>
              Constitute project management, financial, legal, or other
              professional advice
            </li>
            <li>
              Train on your data — Anthropic does not use API inputs to
              train models
            </li>
          </ul>

          <p className="pt-2 text-h3 text-ink">How to use it well</p>
          <ul className="ml-5 list-disc space-y-1">
            <li>Treat AI Analysis as a starting point, not a final answer</li>
            <li>
              Cross-check identified risks against your own knowledge of the
              project
            </li>
            <li>
              Use recommendations as prompts for your own thinking, not as
              instructions
            </li>
            <li>Re-run analysis after meaningful plan changes (Pro feature)</li>
          </ul>

          <p className="pt-2 text-caption text-slate-500">
            For full details, see our{" "}
            <a
              href="/products/plansight-ai/legal/terms"
              className="font-semibold text-slate-700 underline-offset-2 transition hover:text-cyan-700 hover:underline"
            >
              Terms of Service section 6
            </a>
            .
          </p>
        </div>

        <div className="mt-6 flex justify-end">
          <button
            type="button"
            onClick={onClose}
            className="inline-flex h-9 items-center rounded-md bg-cyan-700 px-4 text-body font-semibold text-white transition hover:bg-cyan-800"
          >
            Got it
          </button>
        </div>
      </div>
    </div>
  );
}
