"use client";

import { Info, X } from "lucide-react";
import { useEffect, useState } from "react";

type Props = {
  /**
   * `"full"` — three-sentence banner for the AI Analysis tab.
   * `"compact"` — single-line phrasing for in-modal use (e.g. ExplainTaskModal).
   */
  variant?: "full" | "compact";
  /**
   * When true, renders an `×` dismiss control. Dismissal persists in
   * sessionStorage for the rest of the browser session, then resets on
   * next session. Pass `false` on surfaces where the user can't be
   * expected to opt out (modals, share views).
   */
  dismissible?: boolean;
};

const SESSION_STORAGE_KEY = "plansight:disclaimer:ai-analysis:dismissed";

/**
 * In-product disclaimer for AI-generated output. See
 * docs/plansight-ai/specs/IN_PRODUCT_DISCLAIMERS_SPEC.md for the legal
 * and tone reasoning behind the copy. Two variants only:
 *
 * - `full` (default) — used at the top of the AI Analysis tab.
 * - `compact` — used inside the Explain-this-Task modal where vertical
 *   space is constrained.
 */
export function AiAnalysisDisclaimer({
  variant = "full",
  dismissible = false
}: Props) {
  const [hidden, setHidden] = useState(false);

  useEffect(() => {
    if (!dismissible) return;
    try {
      if (window.sessionStorage.getItem(SESSION_STORAGE_KEY) === "1") {
        setHidden(true);
      }
    } catch {
      // sessionStorage unavailable — keep the banner visible.
    }
  }, [dismissible]);

  if (hidden) return null;

  const handleDismiss = () => {
    try {
      window.sessionStorage.setItem(SESSION_STORAGE_KEY, "1");
    } catch {
      // Best-effort; still hide for this render so the click feels right.
    }
    setHidden(true);
  };

  return (
    <div className="flex items-start gap-3 rounded-md border border-cyan-200 bg-cyan-50/60 p-4 text-body text-slate-700">
      <Info className="mt-0.5 h-4 w-4 shrink-0 text-cyan-700" />
      <div className="min-w-0 flex-1">
        {variant === "full" ? (
          <p>
            Generated by Claude from your plan data. Review carefully and
            apply your own judgement before sharing with stakeholders or
            making project decisions. Not a substitute for professional
            project management expertise.
          </p>
        ) : (
          <p>Generated by AI. Cross-check before acting on it.</p>
        )}
      </div>
      {dismissible ? (
        <button
          type="button"
          onClick={handleDismiss}
          aria-label="Dismiss disclaimer for this session"
          className="inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-md text-slate-500 transition hover:bg-cyan-100 hover:text-slate-700"
        >
          <X className="h-3.5 w-3.5" />
        </button>
      ) : null}
    </div>
  );
}
