import type { Plan } from "./types";

export const demoPlan: Plan = {
  id: "plansight-ai-demo-001",
  title: "Enterprise Portfolio Refresh",
  sourceFormat: "mpp",
  importedAt: "2026-04-29T08:00:00.000Z",
  startDate: "2026-04-06",
  finishDate: "2026-05-22",
  tasks: [
    {
      id: 1,
      uniqueId: 1001,
      parentId: null,
      name: "Enterprise Portfolio Refresh",
      outlineLevel: 1,
      outlineNumber: "1",
      wbs: "1",
      start: "2026-04-06",
      finish: "2026-05-22",
      duration: "7w",
      percentComplete: 42,
      summary: true,
      milestone: false,
      predecessors: [],
      resourceNames: ["Program Management Office"]
    },
    {
      id: 2,
      uniqueId: 1002,
      parentId: 1,
      name: "Scope and stakeholder alignment",
      outlineLevel: 2,
      outlineNumber: "1.1",
      wbs: "1.1",
      start: "2026-04-06",
      finish: "2026-04-12",
      duration: "1w",
      percentComplete: 100,
      summary: false,
      milestone: false,
      predecessors: [],
      resourceNames: ["Angelito Crisologo"]
    },
    {
      id: 3,
      uniqueId: 1003,
      parentId: 1,
      name: "Data cleanup and schedule validation",
      outlineLevel: 2,
      outlineNumber: "1.2",
      wbs: "1.2",
      start: "2026-04-13",
      finish: "2026-04-24",
      duration: "2w",
      percentComplete: 75,
      summary: false,
      milestone: false,
      predecessors: [{ predecessorTaskId: 2, type: "FS", lag: "0d" }],
      resourceNames: ["Project Controls"]
    },
    {
      id: 4,
      uniqueId: 1004,
      parentId: 1,
      name: "Executive review checkpoint",
      outlineLevel: 2,
      outlineNumber: "1.3",
      wbs: "1.3",
      start: "2026-04-25",
      finish: "2026-04-25",
      duration: "0d",
      percentComplete: 0,
      summary: false,
      milestone: true,
      predecessors: [{ predecessorTaskId: 3, type: "FS", lag: "0d" }],
      resourceNames: ["Leadership"]
    },
    {
      id: 5,
      uniqueId: 1005,
      parentId: 1,
      name: "Stakeholder-ready summary",
      outlineLevel: 2,
      outlineNumber: "1.4",
      wbs: "1.4",
      start: "2026-04-28",
      finish: "2026-05-02",
      duration: "1w",
      percentComplete: 20,
      summary: false,
      milestone: false,
      predecessors: [{ predecessorTaskId: 4, type: "FS", lag: "0d" }],
      resourceNames: ["Angelito Crisologo", "Comms"]
    },
    {
      id: 6,
      uniqueId: 1006,
      parentId: 1,
      name: "Stakeholder distribution",
      outlineLevel: 2,
      outlineNumber: "1.5",
      wbs: "1.5",
      start: null,
      finish: null,
      duration: null,
      percentComplete: 0,
      summary: false,
      milestone: false,
      predecessors: [{ predecessorTaskId: 5, type: "FS", lag: "1d" }],
      resourceNames: []
    }
  ]
};
