"use client";

import { AlertCircle, Loader2, MessageSquare, RefreshCcw, Sparkles, TriangleAlert } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import type { AiAnalysis } from "@/lib/plansight-ai/ai";

type Props = {
  shareId: string;
  selectedTaskIds: Set<number>;
  onSelectTasks: (taskIds: number[]) => void;
};

type LoadState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "success"; analysis: AiAnalysis; cached: boolean }
  | { status: "error"; message: string };

export function PlanSightAIAnalysisPanel({ shareId, selectedTaskIds, onSelectTasks }: Props) {
  const [state, setState] = useState<LoadState>({ status: "idle" });

  const fetchAnalysis = useCallback(async (options?: { force?: boolean }) => {
    setState({ status: "loading" });

    try {
      const response = await fetch("/api/plansight/ai-analysis", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ shareId, force: options?.force ?? false })
      });

      const payload = (await response.json().catch(() => ({}))) as {
        analysis?: AiAnalysis;
        cached?: boolean;
        error?: string;
      };

      if (!response.ok || !payload.analysis) {
        throw new Error(payload.error || "Failed to load AI analysis.");
      }

      setState({
        status: "success",
        analysis: payload.analysis,
        cached: !!payload.cached
      });
    } catch (error) {
      setState({
        status: "error",
        message: error instanceof Error ? error.message : "Failed to load AI analysis."
      });
    }
  }, [shareId]);

  useEffect(() => {
    void fetchAnalysis();
  }, [fetchAnalysis]);

  const regenerate = () => fetchAnalysis({ force: true });

  return (
    <section className="px-6 py-10">
      <div className="mx-auto grid max-w-[1200px] gap-6 xl:grid-cols-[1.2fr_0.8fr]">
        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft">
          <div className="flex items-center justify-between gap-3">
            <div className="flex items-center gap-3">
              <div className="inline-flex h-11 w-11 items-center justify-center rounded-2xl bg-primary/10 text-primary">
                <MessageSquare className="h-5 w-5" />
              </div>
              <div>
                <p className="text-sm font-semibold uppercase tracking-normal text-primary">
                  AI summary
                </p>
                <h3 className="text-xl font-semibold text-dark">Generated by Claude</h3>
              </div>
            </div>

            {state.status === "success" ? (
              <button
                type="button"
                onClick={regenerate}
                className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-600 transition hover:bg-slate-50"
                title="Force a fresh Claude call (bypasses cache)"
              >
                <RefreshCcw className="h-3.5 w-3.5" />
                Regenerate
              </button>
            ) : null}
          </div>

          <div className="mt-5 rounded-2xl bg-slate-50 p-5">
            {state.status === "loading" || state.status === "idle" ? (
              <div className="flex items-center gap-3 text-sm text-slate-600">
                <Loader2 className="h-4 w-4 animate-spin text-primary" />
                <span>Generating AI analysis...</span>
              </div>
            ) : state.status === "error" ? (
              <div className="space-y-3">
                <div className="flex items-start gap-3 text-sm text-red-700">
                  <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
                  <span>{state.message}</span>
                </div>
                <button
                  type="button"
                  onClick={() => fetchAnalysis()}
                  className="inline-flex items-center gap-2 rounded-full bg-primary px-4 py-1.5 text-xs font-semibold text-white transition hover:bg-primary/90"
                >
                  <RefreshCcw className="h-3.5 w-3.5" />
                  Try again
                </button>
              </div>
            ) : (
              <p className="text-base leading-7 text-slate-700">{state.analysis.summary}</p>
            )}
          </div>

          {state.status === "success" ? (
            <div className="mt-5">
              <RisksList
                risks={state.analysis.risks}
                selectedTaskIds={selectedTaskIds}
                onSelectTasks={onSelectTasks}
              />
            </div>
          ) : null}
        </div>

        <div className="grid gap-6">
          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft">
            <div className="flex items-center gap-3">
              <div className="inline-flex h-11 w-11 items-center justify-center rounded-2xl bg-secondary/10 text-secondary">
                <Sparkles className="h-5 w-5" />
              </div>
              <div>
                <p className="text-sm font-semibold uppercase tracking-normal text-secondary">
                  Recommendations
                </p>
                <h3 className="text-xl font-semibold text-dark">Suggested next actions</h3>
              </div>
            </div>

            {state.status === "loading" || state.status === "idle" ? (
              <div className="mt-4 flex items-center gap-2 text-sm text-slate-500">
                <Loader2 className="h-4 w-4 animate-spin" />
                <span>Generating...</span>
              </div>
            ) : state.status === "success" ? (
              state.analysis.recommendations.length > 0 ? (
                <ul className="mt-4 space-y-3 text-sm leading-6 text-slate-600">
                  {state.analysis.recommendations.map((recommendation, index) => (
                    <li key={index} className="rounded-2xl bg-slate-50 px-4 py-3">
                      <p className="font-medium text-dark">{recommendation.action}</p>
                      <p className="mt-1 text-slate-600">{recommendation.rationale}</p>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="mt-4 rounded-2xl bg-slate-50 px-4 py-3 text-sm text-slate-500">
                  The analysis didn&apos;t return specific recommendations. Try regenerating.
                </p>
              )
            ) : null}
          </div>

          {state.status === "success" && state.analysis.generatedAt ? (
            <p className="text-xs text-slate-400">
              Generated {formatRelativeTime(state.analysis.generatedAt)}
              {state.cached ? " · cached" : ""}
            </p>
          ) : null}
        </div>
      </div>
    </section>
  );
}

function RisksList({
  risks,
  selectedTaskIds,
  onSelectTasks
}: {
  risks: AiAnalysis["risks"];
  selectedTaskIds: Set<number>;
  onSelectTasks: (taskIds: number[]) => void;
}) {
  if (risks.length === 0) {
    return (
      <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600">
        No major risks identified by the AI analysis.
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-5">
      <div className="flex items-center gap-2">
        <TriangleAlert className="h-4 w-4 text-slate-500" />
        <p className="text-sm font-semibold uppercase tracking-normal text-dark">Risks</p>
      </div>
      <ul className="mt-3 space-y-3 text-sm leading-6 text-slate-700">
        {risks.map((risk, index) => {
          const taskIds = risk.taskIds ?? [];
          const anyHighlighted = taskIds.some((id) => selectedTaskIds.has(id));

          return (
            <li
              key={index}
              className={`rounded-2xl border px-4 py-3 ${
                anyHighlighted ? "border-secondary/40 bg-secondary/5" : "border-slate-100 bg-slate-50"
              }`}
            >
              <p className="font-medium text-dark">{risk.title}</p>
              <p className="mt-1 text-slate-600">{risk.explanation}</p>
              {taskIds.length > 0 ? (
                <button
                  type="button"
                  onClick={() => onSelectTasks(taskIds)}
                  className="mt-2 inline-flex items-center gap-2 rounded-full bg-white px-3 py-1 text-xs font-medium text-secondary transition hover:bg-secondary/10"
                >
                  Highlight {taskIds.length} task{taskIds.length === 1 ? "" : "s"}
                </button>
              ) : null}
            </li>
          );
        })}
      </ul>
    </div>
  );
}

function formatRelativeTime(iso: string) {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return "just now";

  const seconds = Math.max(0, Math.floor((Date.now() - date.getTime()) / 1000));
  if (seconds < 60) return "just now";
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes} min ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours} hr ago`;
  const days = Math.floor(hours / 24);
  return `${days} day${days === 1 ? "" : "s"} ago`;
}
