"use client";

import { AlertCircle, Loader2, Lock, MessageSquare, RefreshCcw, Sparkles, TriangleAlert } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import type { AiAnalysis } from "@/lib/plansight-ai/ai";

type Props = {
  shareId: string;
  selectedTaskIds: Set<number>;
  onSelectTasks: (taskIds: number[]) => void;
  /**
   * Whether the current user can force a fresh Claude call (bypassing cache).
   * Regenerate is a Pro-tier feature. Phase 4 (auth) will derive this from
   * the user session. Defaults to false today.
   */
  canRegenerate?: boolean;
};

type LoadState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "success"; analysis: AiAnalysis; cached: boolean }
  | { status: "error"; message: string };

// Preview-only escape hatch for prompt-iteration testing during validation.
// Set NEXT_PUBLIC_PLANSIGHT_DEV_REGENERATE=true on the Vercel Preview env to
// bypass the Pro gate and exercise fresh Claude calls. NEVER set this in
// Production. Phase 4 (auth) replaces this with a real session.tier check.
const DEV_BYPASS_ENABLED =
  process.env.NEXT_PUBLIC_PLANSIGHT_DEV_REGENERATE === "true";

export function PlanSightAIAnalysisPanel({
  shareId,
  selectedTaskIds,
  onSelectTasks,
  canRegenerate: canRegenerateProp = false
}: Props) {
  const canRegenerate = canRegenerateProp || DEV_BYPASS_ENABLED;
  const [state, setState] = useState<LoadState>({ status: "idle" });
  const [showProGate, setShowProGate] = useState(false);

  const fetchAnalysis = useCallback(async (options?: { force?: boolean }) => {
    setState({ status: "loading" });

    try {
      const response = await fetch("/api/plansight/ai-analysis", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ shareId, force: options?.force ?? false })
      });

      const payload = (await response.json().catch(() => ({}))) as {
        analysis?: AiAnalysis;
        cached?: boolean;
        error?: string;
      };

      if (!response.ok || !payload.analysis) {
        throw new Error(payload.error || "Failed to load AI analysis.");
      }

      setState({
        status: "success",
        analysis: payload.analysis,
        cached: !!payload.cached
      });
    } catch (error) {
      setState({
        status: "error",
        message: error instanceof Error ? error.message : "Failed to load AI analysis."
      });
    }
  }, [shareId]);

  useEffect(() => {
    void fetchAnalysis();
  }, [fetchAnalysis]);

  const regenerate = () => fetchAnalysis({ force: true });

  const handleRegenerateClick = () => {
    if (canRegenerate) {
      setShowProGate(false);
      regenerate();
    } else {
      setShowProGate(true);
    }
  };

  return (
    <section className="px-6 py-10">
      <div className="mx-auto grid max-w-[1200px] gap-6 xl:grid-cols-[1.2fr_0.8fr]">
        <div className="flex flex-col rounded-xl border border-slate-200 bg-white p-6 xl:h-[640px]">
          <div className="flex shrink-0 items-center justify-between gap-3">
            <div className="flex items-center gap-3">
              <div className="inline-flex h-10 w-10 items-center justify-center rounded-md bg-cyan-50 text-cyan-700">
                <MessageSquare className="h-5 w-5" />
              </div>
              <div>
                <p className="text-micro text-cyan-700">AI summary</p>
                <h3 className="text-h3 text-ink">Generated by Claude</h3>
              </div>
            </div>

            {state.status === "success" ? (
              <button
                type="button"
                onClick={handleRegenerateClick}
                className={
                  canRegenerate
                    ? "inline-flex h-9 items-center gap-2 rounded-md border border-slate-200 bg-white px-3 text-body font-semibold text-slate-700 transition hover:border-slate-300 hover:bg-slate-50"
                    : "inline-flex h-9 items-center gap-2 rounded-md border border-slate-200 bg-slate-50 px-3 text-body font-semibold text-slate-500 transition hover:bg-slate-100"
                }
                title={
                  canRegenerate
                    ? "Force a fresh Claude call (bypasses cache)"
                    : "Regenerate is a Pro feature"
                }
              >
                {canRegenerate ? (
                  <RefreshCcw className="h-3.5 w-3.5" />
                ) : (
                  <Lock className="h-3.5 w-3.5" />
                )}
                <span>Regenerate</span>
                {!canRegenerate ? (
                  <span className="rounded border border-cyan-200 bg-cyan-50 px-1.5 py-0.5 text-micro text-cyan-700">
                    Pro
                  </span>
                ) : null}
              </button>
            ) : null}
          </div>

          {showProGate ? (
            <div className="mt-5 shrink-0 rounded-md border border-slate-200 bg-slate-50 p-5">
              <div className="flex items-start gap-3">
                <div className="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-cyan-50 text-cyan-700">
                  <Sparkles className="h-4 w-4" />
                </div>
                <div className="min-w-0 flex-1">
                  <p className="text-h3 text-ink">Regenerate is a Pro feature</p>
                  <p className="mt-1 text-body text-slate-700">
                    Each plan gets one AI analysis at no cost. Re-runs are reserved
                    for Pro — upgrade to regenerate with the latest model output.
                  </p>
                  <div className="mt-3 flex flex-wrap gap-2">
                    <a
                      href="/upgrade"
                      className="inline-flex h-9 items-center gap-2 rounded-md bg-cyan-700 px-3 text-body font-semibold text-white transition hover:bg-cyan-800"
                    >
                      Upgrade to Pro
                    </a>
                    <button
                      type="button"
                      onClick={() => setShowProGate(false)}
                      className="inline-flex h-9 items-center rounded-md border border-slate-200 bg-white px-3 text-body font-semibold text-slate-700 transition hover:border-slate-300 hover:bg-slate-50"
                    >
                      Dismiss
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ) : null}

          <div className="mt-5 flex flex-col gap-5 overflow-y-auto pr-1 xl:min-h-0 xl:flex-1">
            <div className="shrink-0 rounded-md bg-slate-50 p-5">
              {state.status === "loading" || state.status === "idle" ? (
                <div className="flex items-center gap-3 text-body text-slate-700">
                  <Loader2 className="h-4 w-4 animate-spin text-cyan-700" />
                  <span>Generating analysis (5–8s)...</span>
                </div>
              ) : state.status === "error" ? (
                <div className="space-y-3">
                  <div className="flex items-start gap-3 text-body text-red-800">
                    <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
                    <span>{state.message}</span>
                  </div>
                  <button
                    type="button"
                    onClick={() => fetchAnalysis()}
                    className="inline-flex h-9 items-center gap-2 rounded-md bg-cyan-700 px-3 text-body font-semibold text-white transition hover:bg-cyan-800"
                  >
                    <RefreshCcw className="h-3.5 w-3.5" />
                    Try again
                  </button>
                </div>
              ) : (
                <p className="text-body-lg text-slate-700">{state.analysis.summary}</p>
              )}
            </div>

            {state.status === "success" ? (
              <RisksList
                risks={state.analysis.risks}
                selectedTaskIds={selectedTaskIds}
                onSelectTasks={onSelectTasks}
              />
            ) : null}
          </div>
        </div>

        <div className="flex flex-col gap-3">
          <div className="flex flex-col rounded-xl border border-slate-200 bg-white p-6 xl:h-[640px]">
            <div className="flex shrink-0 items-center gap-3">
              <div className="inline-flex h-10 w-10 items-center justify-center rounded-md bg-cyan-50 text-cyan-700">
                <Sparkles className="h-5 w-5" />
              </div>
              <div>
                <p className="text-micro text-cyan-700">Recommendations</p>
                <h3 className="text-h3 text-ink">Suggested next actions</h3>
              </div>
            </div>

            <div className="mt-4 overflow-y-auto pr-1 xl:min-h-0 xl:flex-1">
              {state.status === "loading" || state.status === "idle" ? (
                <div className="flex items-center gap-2 text-body text-slate-500">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  <span>Generating...</span>
                </div>
              ) : state.status === "success" ? (
                state.analysis.recommendations.length > 0 ? (
                  <ul className="space-y-3 text-body text-slate-700">
                    {state.analysis.recommendations.map((recommendation, index) => (
                      <li key={index} className="rounded-md bg-slate-50 px-4 py-3">
                        <p className="font-semibold text-ink">{recommendation.action}</p>
                        <p className="mt-1 text-slate-700">{recommendation.rationale}</p>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p className="rounded-md bg-slate-50 px-4 py-3 text-body text-slate-500">
                    The analysis didn&apos;t return specific recommendations. Try regenerating.
                  </p>
                )
              ) : null}
            </div>
          </div>

          {state.status === "success" && state.analysis.generatedAt ? (
            <p className="text-caption text-slate-500">
              Generated{" "}
              <span className="font-mono">
                {formatRelativeTime(state.analysis.generatedAt)}
              </span>
              {state.cached ? " · cached" : ""}
            </p>
          ) : null}
        </div>
      </div>
    </section>
  );
}

function RisksList({
  risks,
  selectedTaskIds,
  onSelectTasks
}: {
  risks: AiAnalysis["risks"];
  selectedTaskIds: Set<number>;
  onSelectTasks: (taskIds: number[]) => void;
}) {
  if (risks.length === 0) {
    return (
      <div className="rounded-md border border-slate-200 bg-slate-50 p-4 text-body text-slate-700">
        No major risks identified.
      </div>
    );
  }

  return (
    <div className="rounded-md border border-slate-200 bg-white p-5">
      <div className="flex items-center gap-2">
        <TriangleAlert className="h-4 w-4 text-slate-500" />
        <p className="text-micro text-ink">Risks</p>
      </div>
      <ul className="mt-3 space-y-3 text-body text-slate-700">
        {risks.map((risk, index) => {
          const taskIds = risk.taskIds ?? [];
          const anyHighlighted = taskIds.some((id) => selectedTaskIds.has(id));

          return (
            <li
              key={index}
              className={`rounded-md border px-4 py-3 ${
                anyHighlighted ? "border-cyan-200 bg-cyan-50" : "border-slate-200 bg-slate-50"
              }`}
            >
              <p className="font-semibold text-ink">{risk.title}</p>
              <p className="mt-1 text-slate-700">{risk.explanation}</p>
              {taskIds.length > 0 ? (
                <div className="mt-2 flex flex-wrap items-center gap-2">
                  <span className="text-caption text-slate-500">
                    Tasks:{" "}
                    {taskIds.map((id, i) => (
                      <span key={id} className="font-mono text-caption text-slate-700">
                        {`t-${String(id).padStart(4, "0")}`}
                        {i < taskIds.length - 1 ? ", " : ""}
                      </span>
                    ))}
                  </span>
                  <button
                    type="button"
                    onClick={() => onSelectTasks(taskIds)}
                    className="inline-flex h-8 items-center gap-2 rounded-md border border-slate-200 bg-white px-3 text-body font-semibold text-slate-700 transition hover:border-slate-300 hover:bg-slate-50"
                  >
                    Highlight in Gantt
                  </button>
                </div>
              ) : null}
            </li>
          );
        })}
      </ul>
    </div>
  );
}

function formatRelativeTime(iso: string) {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return "just now";

  const seconds = Math.max(0, Math.floor((Date.now() - date.getTime()) / 1000));
  if (seconds < 60) return "just now";
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes} min ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours} hr ago`;
  const days = Math.floor(hours / 24);
  return `${days} day${days === 1 ? "" : "s"} ago`;
}
