"use client";

import {
  BellRing,
  BrainCircuit,
  Check,
  FileSpreadsheet,
  GitCompareArrows,
  History,
  LayoutDashboard,
  MessageCircleQuestion,
  Palette,
  RefreshCcw,
  Sparkles,
  TriangleAlert,
  Users,
  X
} from "lucide-react";
import type { ComponentType } from "react";
import { useEffect, useState } from "react";

type AvailabilityStatus = "live" | "pro" | "coming-soon";

type AnalysisFeature = {
  name: string;
  status: AvailabilityStatus;
  description: string;
  icon: ComponentType<{ className?: string }>;
};

const features: AnalysisFeature[] = [
  // Live in the free tier today
  {
    name: "AI summary",
    status: "live",
    icon: Sparkles,
    description:
      "Plain-language narrative of the plan's current state, generated by Claude on every imported plan."
  },
  {
    name: "Risk detection",
    status: "live",
    icon: TriangleAlert,
    description: "Top risks identified with the specific task IDs each one references."
  },
  {
    name: "Recommendations",
    status: "live",
    icon: Check,
    description: "Prescriptive next-step actions for the PM, derived from the analysis."
  },

  // Live in Pro
  {
    name: "My Plans dashboard",
    status: "pro",
    icon: LayoutDashboard,
    description:
      "Upload unlimited plans, see them all in one place, rename, archive, or delete."
  },
  {
    name: "Unlimited retention",
    status: "pro",
    icon: History,
    description:
      "Plans persist as long as your subscription is active. No 14-day auto-delete."
  },
  {
    name: "Regenerate AI",
    status: "pro",
    icon: RefreshCcw,
    description:
      "Re-run the Claude analysis any time after a plan update. Free tier caches the first generation."
  },
  {
    name: "Version compare",
    status: "pro",
    icon: GitCompareArrows,
    description:
      "Upload an updated plan and see what changed — task moves, critical-path shifts, slipping milestones."
  },
  {
    name: "Share analytics",
    status: "pro",
    icon: Users,
    description:
      "Know when stakeholders opened your share link, how long they stayed, and which views they hit."
  },
  {
    name: "Health alerts",
    status: "pro",
    icon: BellRing,
    description:
      "Email notifications when a plan flips to amber or red, or when a critical task goes overdue."
  },
  {
    name: "Custom branding",
    status: "pro",
    icon: Palette,
    description:
      "Your logo, colors, and footer on stakeholder share pages and exported reports."
  },

  // Coming with Pro
  {
    name: "Delay simulation",
    status: "coming-soon",
    icon: BrainCircuit,
    description: "Explore how slipping one task changes downstream timing."
  },
  {
    name: "Natural language Q&A",
    status: "coming-soon",
    icon: MessageCircleQuestion,
    description: "Ask questions about the plan in plain language and get a direct answer."
  },
  {
    name: "XLSX / Smartsheet import",
    status: "coming-soon",
    icon: FileSpreadsheet,
    description: "Import schedules from Excel and Smartsheet alongside .mpp."
  }
];

const FREE_FEATURES = features.filter((f) => f.status === "live");
const PRO_FEATURES = features.filter((f) => f.status === "pro");
const SOON_FEATURES = features.filter((f) => f.status === "coming-soon");

const STATUS_LABELS: Record<AvailabilityStatus, string> = {
  live: "Live",
  pro: "Pro",
  "coming-soon": "Soon"
};

const STATUS_BADGE_CLASSES: Record<AvailabilityStatus, string> = {
  live: "border-emerald-200 bg-emerald-50 text-emerald-700",
  pro: "border-secondary/30 bg-secondary/10 text-secondary",
  "coming-soon": "border-slate-200 bg-slate-50 text-slate-600"
};

type Props = {
  className?: string;
};

export function PremiumAnalysisTeaser({ className = "" }: Props) {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (!open) return;

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        setOpen(false);
      }
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [open]);

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        className={`group w-full rounded-3xl border border-slate-200 bg-white p-6 text-left shadow-soft transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-lg ${className}`.trim()}
      >
        <div className="flex items-start justify-between gap-4">
          <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-dark text-white">
            <BrainCircuit className="h-6 w-6" />
          </div>
          <div className="flex flex-col items-end gap-2">
            <span className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-semibold uppercase tracking-normal text-emerald-700">
              AI is live
            </span>
            <span className="rounded-full border border-secondary/30 bg-secondary/10 px-3 py-1 text-[11px] font-semibold uppercase tracking-normal text-secondary">
              Pro tier ahead
            </span>
          </div>
        </div>

        <div className="mt-5">
          <p className="text-sm font-semibold uppercase tracking-normal text-primary">
            Free vs Pro
          </p>
          <h3 className="mt-2 text-2xl font-semibold text-dark md:text-[28px]">
            Click to compare what&apos;s live and what comes with Pro
          </h3>
          <p className="mt-3 max-w-2xl text-base leading-7 text-slate-600">
            Free covers AI analysis on every imported plan. Pro adds a multi-plan dashboard,
            regeneration, version compare, stakeholder analytics, health alerts, and branded
            shares.
          </p>
        </div>

        <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {features.slice(0, 9).map((feature) => {
            const Icon = feature.icon;
            return (
              <div
                key={feature.name}
                className="flex items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-medium text-dark"
              >
                <span className="flex min-w-0 items-center gap-2">
                  <Icon className="h-4 w-4 shrink-0 text-slate-500" />
                  <span className="truncate">{feature.name}</span>
                </span>
                <span
                  className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${STATUS_BADGE_CLASSES[feature.status]}`}
                >
                  {STATUS_LABELS[feature.status]}
                </span>
              </div>
            );
          })}
        </div>

        <p className="mt-3 text-xs text-slate-500">
          + {features.length - 9} more features in the comparison →
        </p>
      </button>

      {open ? (
        <div
          role="dialog"
          aria-modal="true"
          className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-950/70 px-4 py-6 backdrop-blur-sm"
          onClick={() => setOpen(false)}
        >
          <div
            className="my-auto w-full max-w-4xl rounded-3xl border border-white/10 bg-dark p-6 text-white shadow-2xl"
            onClick={(event) => event.stopPropagation()}
          >
            <div className="flex items-start justify-between gap-4">
              <div>
                <p className="text-sm font-semibold uppercase tracking-normal text-emerald-300">
                  Free vs Pro
                </p>
                <h3 className="mt-2 text-2xl font-semibold">Plan tiers</h3>
                <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">
                  PlanSight runs Claude Haiku 4.5 on every imported plan. Pro unlocks the
                  workspace and stakeholder features PMs need to use it as a daily tool.
                </p>
              </div>
              <button
                type="button"
                onClick={() => setOpen(false)}
                className="inline-flex h-10 w-10 items-center justify-center rounded-full border border-white/10 bg-white/5 text-white transition hover:bg-white/10"
                aria-label="Close tier comparison"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <div className="mt-6 grid gap-4 md:grid-cols-2">
              <TierColumn
                badge="Free"
                badgeClassName="border-emerald-400/40 bg-emerald-400/10 text-emerald-200"
                title="What anyone gets"
                description="Upload, view, share, and read the AI analysis. Each plan's analysis is cached so repeat views don't cost anything."
                features={FREE_FEATURES}
              />
              <TierColumn
                badge="Pro"
                badgeClassName="border-secondary/40 bg-secondary/15 text-amber-200"
                title="Built for PMs who use it daily"
                description="Sign up to unlock the multi-plan workspace, regeneration, and stakeholder tools."
                features={PRO_FEATURES}
              />
            </div>

            <div className="mt-6 rounded-2xl border border-white/10 bg-white/5 p-5">
              <div className="flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-amber-200" />
                <p className="text-sm font-semibold uppercase tracking-normal text-amber-200">
                  Coming with Pro
                </p>
              </div>
              <div className="mt-3 grid gap-3 sm:grid-cols-3">
                {SOON_FEATURES.map((feature) => {
                  const Icon = feature.icon;
                  return (
                    <div
                      key={feature.name}
                      className="rounded-xl border border-white/10 bg-white/5 p-3"
                    >
                      <div className="flex items-center gap-2 text-sm font-semibold text-white">
                        <Icon className="h-4 w-4 text-amber-200" />
                        {feature.name}
                      </div>
                      <p className="mt-1 text-xs leading-5 text-slate-300">
                        {feature.description}
                      </p>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      ) : null}
    </>
  );
}

function TierColumn({
  badge,
  badgeClassName,
  title,
  description,
  features
}: {
  badge: string;
  badgeClassName: string;
  title: string;
  description: string;
  features: AnalysisFeature[];
}) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
      <div className="flex items-center justify-between gap-3">
        <h4 className="text-lg font-semibold text-white">{title}</h4>
        <span
          className={`rounded-full border px-3 py-1 text-[10px] font-semibold uppercase tracking-wide ${badgeClassName}`}
        >
          {badge}
        </span>
      </div>
      <p className="mt-2 text-sm leading-6 text-slate-300">{description}</p>

      <ul className="mt-4 space-y-2.5">
        {features.map((feature) => {
          const Icon = feature.icon;
          return (
            <li key={feature.name} className="flex items-start gap-3 text-sm leading-6">
              <span className="mt-0.5 inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-white/10 text-white">
                <Icon className="h-3.5 w-3.5" />
              </span>
              <div className="min-w-0">
                <p className="font-medium text-white">{feature.name}</p>
                <p className="mt-0.5 text-slate-300">{feature.description}</p>
              </div>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
