"use client";

import { BrainCircuit, Check, ChevronRight, Sparkles, X } from "lucide-react";
import { useEffect, useState } from "react";

type AvailabilityStatus = "live" | "pro" | "coming-soon";

type AnalysisFeature = {
  name: string;
  status: AvailabilityStatus;
  description: string;
};

const features: AnalysisFeature[] = [
  {
    name: "AI summary",
    status: "live",
    description: "Plain-language narrative of the plan's current state, generated by Claude."
  },
  {
    name: "Risk detection",
    status: "live",
    description: "Top risks identified with the specific task IDs each one references."
  },
  {
    name: "Recommendations",
    status: "live",
    description: "Prescriptive next-step actions for the PM, derived from the analysis."
  },
  {
    name: "Regenerate on demand",
    status: "pro",
    description: "Re-run the AI analysis any time after the plan is updated. Free tier caches the first generation."
  },
  {
    name: "Delay simulation",
    status: "coming-soon",
    description: "Explore how slipping one task changes downstream timing."
  },
  {
    name: "Natural language Q&A",
    status: "coming-soon",
    description: "Ask questions about the plan in plain language and get a direct answer."
  }
];

type Props = {
  className?: string;
};

const STATUS_LABELS: Record<AvailabilityStatus, string> = {
  live: "Live",
  pro: "Pro",
  "coming-soon": "Soon"
};

const STATUS_BADGE_CLASSES: Record<AvailabilityStatus, string> = {
  live: "border-emerald-200 bg-emerald-50 text-emerald-700",
  pro: "border-secondary/30 bg-secondary/10 text-secondary",
  "coming-soon": "border-slate-200 bg-slate-50 text-slate-600"
};

export function PremiumAnalysisTeaser({ className = "" }: Props) {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (!open) return;

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        setOpen(false);
      }
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [open]);

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        className={`group w-full rounded-3xl border border-slate-200 bg-white p-6 text-left shadow-soft transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-lg ${className}`.trim()}
      >
        <div className="flex items-start justify-between gap-4">
          <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-dark text-white">
            <BrainCircuit className="h-6 w-6" />
          </div>
          <div className="flex flex-col items-end gap-2">
            <span className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-semibold uppercase tracking-normal text-emerald-700">
              AI is live
            </span>
            <span className="rounded-full border border-secondary/30 bg-secondary/10 px-3 py-1 text-[11px] font-semibold uppercase tracking-normal text-secondary">
              Pro tier ahead
            </span>
          </div>
        </div>

        <div className="mt-5">
          <p className="text-sm font-semibold uppercase tracking-normal text-primary">
            AI Analysis
          </p>
          <h3 className="mt-2 text-2xl font-semibold text-dark md:text-[28px]">
            Click to see what&apos;s in the AI tab
          </h3>
          <p className="mt-3 max-w-2xl text-base leading-7 text-slate-600">
            Summary, risks, and recommendations generate on every imported plan. The Pro tier
            adds regeneration on demand and advanced what-if features.
          </p>
        </div>

        <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((feature) => (
            <div
              key={feature.name}
              className="flex items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-medium text-dark"
            >
              <span className="truncate">{feature.name}</span>
              <span
                className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${STATUS_BADGE_CLASSES[feature.status]}`}
              >
                {STATUS_LABELS[feature.status]}
              </span>
            </div>
          ))}
        </div>
      </button>

      {open ? (
        <div
          role="dialog"
          aria-modal="true"
          className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 px-4 py-6 backdrop-blur-sm"
          onClick={() => setOpen(false)}
        >
          <div
            className="w-full max-w-3xl rounded-3xl border border-white/10 bg-dark p-6 text-white shadow-2xl"
            onClick={(event) => event.stopPropagation()}
          >
            <div className="flex items-start justify-between gap-4">
              <div>
                <p className="text-sm font-semibold uppercase tracking-normal text-emerald-300">
                  AI Analysis
                </p>
                <div className="mt-2 flex items-center gap-3">
                  <h3 className="text-2xl font-semibold">What&apos;s live and what&apos;s next</h3>
                </div>
                <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">
                  PlanSight runs Claude Haiku 4.5 on every imported plan. Each analysis is cached
                  so re-views are free; the Pro tier unlocks fresh re-runs and advanced features.
                </p>
              </div>
              <button
                type="button"
                onClick={() => setOpen(false)}
                className="inline-flex h-10 w-10 items-center justify-center rounded-full border border-white/10 bg-white/5 text-white transition hover:bg-white/10"
                aria-label="Close AI analysis preview"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <div className="mt-6 grid gap-3 md:grid-cols-2">
              {features.map((feature) => (
                <div key={feature.name} className="rounded-2xl border border-white/10 bg-white/5 p-4">
                  <div className="flex items-start justify-between gap-3">
                    <p className="text-sm font-semibold text-white">{feature.name}</p>
                    <span
                      className={`shrink-0 rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${
                        feature.status === "live"
                          ? "border-emerald-400/40 bg-emerald-400/10 text-emerald-200"
                          : feature.status === "pro"
                            ? "border-secondary/40 bg-secondary/15 text-amber-200"
                            : "border-white/15 bg-white/5 text-slate-300"
                      }`}
                    >
                      {STATUS_LABELS[feature.status]}
                    </span>
                  </div>
                  <p className="mt-2 text-sm leading-6 text-slate-300">{feature.description}</p>
                </div>
              ))}
            </div>

            <div className="mt-6 flex flex-col gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm leading-6 text-slate-300 md:flex-row md:items-start md:gap-4">
              <div className="inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-emerald-400/15 text-emerald-200">
                <Check className="h-4 w-4" />
              </div>
              <p>
                <span className="font-semibold text-white">Free tier:</span> upload, view,
                share, and read the AI analysis. Each plan&apos;s analysis is cached so repeat
                views don&apos;t cost anything.
              </p>
            </div>

            <div className="mt-3 flex flex-col gap-3 rounded-2xl border border-secondary/30 bg-secondary/10 p-4 text-sm leading-6 text-slate-200 md:flex-row md:items-start md:gap-4">
              <div className="inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-secondary/20 text-secondary">
                <Sparkles className="h-4 w-4" />
              </div>
              <p>
                <span className="font-semibold text-white">Pro tier:</span> regenerate the AI
                analysis any time. Advanced what-if features (delay simulation, natural-language
                Q&amp;A) coming with the Pro release.
              </p>
            </div>
          </div>
        </div>
      ) : null}
    </>
  );
}
