"use client";

import {
  BrainCircuit,
  Check,
  FileBarChart,
  FileText,
  History,
  LayoutDashboard,
  RefreshCcw,
  Sparkles,
  TriangleAlert,
  Upload,
  X
} from "lucide-react";
import type { ComponentType } from "react";
import { useEffect, useState } from "react";

type AvailabilityStatus = "live" | "pro";

type AnalysisFeature = {
  name: string;
  status: AvailabilityStatus;
  description: string;
  icon: ComponentType<{ className?: string }>;
};

const features: AnalysisFeature[] = [
  // Live in the free tier today
  {
    name: "AI summary",
    status: "live",
    icon: Sparkles,
    description:
      "Plain-language narrative of the plan's current state, generated by Claude on every imported plan."
  },
  {
    name: "Risk detection",
    status: "live",
    icon: TriangleAlert,
    description: "Top risks identified with the specific task IDs each one references."
  },
  {
    name: "Recommendations",
    status: "live",
    icon: Check,
    description: "Prescriptive next-step actions for the PM, derived from the analysis."
  },

  // Live in Pro
  {
    name: "My Plans dashboard",
    status: "pro",
    icon: LayoutDashboard,
    description:
      "Open any past plan from one place — workspace, insights, and AI analysis. Free signed-in users see only their most recent plan; Pro keeps them all."
  },
  {
    name: "Multi-plan retention",
    status: "pro",
    icon: History,
    description:
      "Pro keeps every plan you import with stable share URLs. Free replaces your previous plan on each import and breaks the old share link."
  },
  {
    name: "Regenerate AI",
    status: "pro",
    icon: RefreshCcw,
    description:
      "Re-run the Claude analysis any time after a plan update. Free caches the first generation only — Pro keeps the analysis in sync."
  },
  {
    name: "Explain this task",
    status: "pro",
    icon: Sparkles,
    description:
      "Click the spark on any task in the workspace and Claude explains it in plain language using its dependency neighbourhood."
  },
  {
    name: "Export PDF",
    status: "pro",
    icon: FileText,
    description:
      "Landscape A4 with ID, task name, dates, % complete, resource, and notes — outline-indented like MS Project."
  },
  {
    name: "Weekly Status Report",
    status: "pro",
    icon: FileBarChart,
    description:
      "One-page PDF covering the last completed week: RAG, slips, at-risk tasks, milestone hit/miss, and an AI-written Status Summary."
  },
  {
    name: "Higher upload limits",
    status: "pro",
    icon: Upload,
    description:
      "25 MB files and up to 25,000 tasks per plan, vs 5 MB / 5,000 on Free. Built for enterprise programs and consolidated portfolios."
  }
];

const FREE_FEATURES = features.filter((f) => f.status === "live");
const PRO_FEATURES = features.filter((f) => f.status === "pro");

const STATUS_LABELS: Record<AvailabilityStatus, string> = {
  live: "Live",
  pro: "Pro"
};

const STATUS_BADGE_CLASSES: Record<AvailabilityStatus, string> = {
  live: "border-emerald-200 bg-emerald-50 text-emerald-800",
  pro: "border-cyan-200 bg-cyan-50 text-cyan-700"
};

type Props = {
  className?: string;
};

export function PremiumAnalysisTeaser({ className = "" }: Props) {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (!open) return;

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        setOpen(false);
      }
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [open]);

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        className={`group w-full rounded-xl border border-slate-200 bg-white p-6 text-left transition hover:border-slate-300 ${className}`.trim()}
      >
        <div className="flex items-start justify-between gap-4">
          <div className="inline-flex h-12 w-12 items-center justify-center rounded-md bg-navy text-cyan-400">
            <BrainCircuit className="h-6 w-6" />
          </div>
          <div className="flex flex-col items-end gap-2">
            <span className="rounded border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-micro text-emerald-800">
              AI is live
            </span>
            <span className="rounded border border-cyan-200 bg-cyan-50 px-2 py-0.5 text-micro text-cyan-700">
              Pro tier ahead
            </span>
          </div>
        </div>

        <div className="mt-5">
          <p className="text-micro text-cyan-700">Free vs Pro</p>
          <h3 className="mt-2 text-h1 text-ink">
            Compare what&apos;s live and what comes with Pro
          </h3>
          <p className="mt-3 max-w-2xl text-body-lg text-slate-700">
            Free signed-in PMs keep one plan slot — the latest import is always
            available when they return. Pro adds the multi-plan dashboard,
            regeneration on demand, inline AI per task, landscape PDF export,
            AI-narrated weekly status reports, and higher upload limits.
          </p>
        </div>

        <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {features.slice(0, 9).map((feature) => {
            const Icon = feature.icon;
            return (
              <div
                key={feature.name}
                className="flex items-center justify-between gap-3 rounded-md border border-slate-200 bg-slate-50 px-3 py-2.5 text-body font-semibold text-ink"
              >
                <span className="flex min-w-0 items-center gap-2">
                  <Icon className="h-4 w-4 shrink-0 text-slate-500" />
                  <span className="truncate">{feature.name}</span>
                </span>
                <span
                  className={`rounded border px-2 py-0.5 text-micro ${STATUS_BADGE_CLASSES[feature.status]}`}
                >
                  {STATUS_LABELS[feature.status]}
                </span>
              </div>
            );
          })}
        </div>

        {features.length > 9 ? (
          <p className="mt-3 text-caption text-slate-500">
            + {features.length - 9} more feature
            {features.length - 9 === 1 ? "" : "s"} in the comparison →
          </p>
        ) : (
          <p className="mt-3 text-caption text-slate-500">
            Open the full comparison →
          </p>
        )}
      </button>

      {open ? (
        <div
          role="dialog"
          aria-modal="true"
          className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-navy/70 px-4 py-6 backdrop-blur-sm"
          onClick={() => setOpen(false)}
        >
          <div
            className="my-auto w-full max-w-4xl rounded-xl border border-slate-800 bg-navy p-6 text-slate-100 shadow-modal"
            onClick={(event) => event.stopPropagation()}
          >
            <div className="flex items-start justify-between gap-4">
              <div>
                <p className="text-micro text-cyan-400">Free vs Pro</p>
                <h3 className="mt-2 text-h2 text-slate-100">Plan tiers</h3>
                <p className="mt-3 max-w-2xl text-body text-slate-300">
                  PlanSight runs Claude Haiku 4.5 on every imported plan. Pro unlocks
                  the workspace and stakeholder features PMs need to use it as a
                  daily tool.
                </p>
              </div>
              <button
                type="button"
                onClick={() => setOpen(false)}
                className="inline-flex h-10 w-10 items-center justify-center rounded-md border border-slate-800 bg-navy-800 text-slate-200 transition hover:border-slate-700 hover:bg-slate-800"
                aria-label="Close tier comparison"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <div className="mt-6 grid gap-4 md:grid-cols-2">
              <TierColumn
                badge="Free"
                badgeClassName="border-emerald-700 bg-emerald-900/40 text-emerald-200"
                title="Use the full workspace today"
                description="Anyone can upload, view, and read the AI analysis. Sign in to keep your most recent plan accessible across sessions — one plan slot, replaced when you import a new one."
                features={FREE_FEATURES}
              />
              <TierColumn
                badge="Pro"
                badgeClassName="border-cyan-700 bg-cyan-900/30 text-cyan-300"
                title="Multi-plan workflow for daily PMs"
                description="Pro keeps every plan you upload, regenerates the AI on demand, adds Explain-this-task inline AI, exports landscape PDFs, generates weekly status reports, and raises upload limits to 25 MB / 25,000 tasks."
                features={PRO_FEATURES}
              />
            </div>

          </div>
        </div>
      ) : null}
    </>
  );
}

function TierColumn({
  badge,
  badgeClassName,
  title,
  description,
  features
}: {
  badge: string;
  badgeClassName: string;
  title: string;
  description: string;
  features: AnalysisFeature[];
}) {
  return (
    <div className="rounded-md border border-slate-800 bg-navy-800 p-5">
      <div className="flex items-center justify-between gap-3">
        <h4 className="text-h3 text-slate-100">{title}</h4>
        <span
          className={`rounded border px-2 py-0.5 text-micro ${badgeClassName}`}
        >
          {badge}
        </span>
      </div>
      <p className="mt-2 text-body text-slate-400">{description}</p>

      <ul className="mt-4 space-y-2.5">
        {features.map((feature) => {
          const Icon = feature.icon;
          return (
            <li key={feature.name} className="flex items-start gap-3 text-body">
              <span className="mt-0.5 inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-slate-800 text-cyan-400">
                <Icon className="h-3.5 w-3.5" />
              </span>
              <div className="min-w-0">
                <p className="font-semibold text-slate-100">{feature.name}</p>
                <p className="mt-0.5 text-slate-400">{feature.description}</p>
              </div>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
